title: Abhishek Murti
description: Computational biologist | UCSF | Projects, publications, and packages
theme: jekyll-theme-minimal
show_downloads: true

author:
  name: Abhishek Murti
  email: murtiabhishek@gmail.com
  github: https://github.com/murti-abhishek
  linkedin: https://www.linkedin.com/in/abhishek-murti/
  strava: https://www.strava.com/athletes/84323856
