title: Abhishek Murti
description: Computational Biologist | San Francisco
author:
  name: Abhishek Murti
  email: murtiabhishek@gmail.com
url: "https://murti-abhishek.github.io"
baseurl: ""
theme: jekyll-theme-hyde
plugins:
  - jekyll-feed

# title: Abhishek Murti
# description: Computational biologist | UCSF
# theme: jekyll-theme-minimal
# show_downloads: true
